<a href="https://colab.research.google.com/github/Rheartscoding/Fall24-Data-Science-Bootcamp-HW/blob/main/DataScience_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

From the DataFrame df, filter the 'Manufacturer', 'Model', and 'Type' for every 20th row starting from the 1st row (row 0):

In [ ]:

import pandas as pd

# Read the DataFrame from the provided URL
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter the 'Manufacturer', 'Model', and 'Type' columns for every 20th row starting from the 1st row
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


Replace missing values in Min.Price and Max.Price columns with their respective mean

In [ ]:

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


<ipython-input-2-89841bb278c5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-2-89841bb278c5>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)'

3)How to get the rows of a dataframe with row sum > 100? df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))


In [ ]:
import numpy as np
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
row_sum_gt_100 = df[df.sum(axis=1) > 100]
print(row_sum_gt_100)

     0   1   2   3
0   39  37  27  38
1   30  33  21  25
2   27  16  18  16
3   32  30  19  38
4   21  36  24  29
5   29  33  21  12
6   31  24  28  19
7   39  28  27  32
8   27  33  27  32
9   37  15  22  11
10  38  27  19  33
11  17  17  29  11
12  29  33  17  17
13  17  10  15  17
14  31  34  10  38
     0   1   2   3
0   39  37  27  38
1   30  33  21  25
3   32  30  19  38
4   21  36  24  29
6   31  24  28  19
7   39  28  27  32
8   27  33  27  32
10  38  27  19  33
14  31  34  10  38


Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays:

In [ ]:
# Creating a 4x4 NumPy array filled with random integers between 1 and 100
data = np.random.randint(1, 101, (4, 4))

# Reshaping the array into separate arrays representing rows and columns
rows = data.reshape(4, 4)
columns = data.T.reshape(4, 4)

# Defining a lambda function to calculate the sum of rows and columns. Notice the axis
sum_rows = lambda array: np.sum(array, axis=1)
sum_columns = lambda array: np.sum(array, axis=1)

# Calculate the sum of each row and column separately
sum_of_rows = sum_rows(rows)
sum_of_columns = sum_columns(columns)

print(" Original Array:",data)
print("Sum of rows:", sum_of_rows)
print("Sum of columns:", sum_of_columns)

 Original Array: [[37 90 55 80]
 [47  6 65  5]
 [90 83 77 86]
 [93 41 43 40]]
Sum of rows: [262 123 336 217]
Sum of columns: [267 220 240 211]
